chunk_duration_seconds: 30
output_height: null
temp_dir: /tmp/vybe-camera-agent
web_port: 5174
storage_mode: upload
output_dir: ${OUTPUT_DIR}
venue_id: 48c2fcac-b0e6-47e6-935a-762b9925e411
api_base_url: http://localhost:8081
keycloak_url: http://localhost:8080
keycloak_realm: vybe
keycloak_client_id: camera-agent-48c2fcac-b0e6-47e6-935a-762b9925e411-1776202128396
keycloak_client_secret: BEiN5lRzNLvIXtEUGYn9KALGWsqqvNMG
