chunk_duration_seconds: 30
output_height: null
temp_dir: /tmp/vybe-camera-agent
web_port: 5174
storage_mode: upload
output_dir: ${OUTPUT_DIR}
venue_id: 3ae77742-2346-4368-b28d-e08d320e6afb
api_base_url: http://localhost:8081
keycloak_url: http://localhost:8080
keycloak_realm: vybe
keycloak_client_id: camera-agent-3ae77742-2346-4368-b28d-e08d320e6afb-1775742438165
keycloak_client_secret: aVCDWSGb21hluZQPOJDHeNQFCWqRpRk2
